app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', [
	'as' 	=>	'index', 
	'uses'	=>	'MainController@index'
	]);
	
Route::get('about', [
		'uses'	=>	'MainController@about',
		'as'	=>	'about'
	]);
	
Route::get('contact', [
		'uses'	=>	'ContactController@index',
		'as'	=>	'contact.index'
	]);
	
Route::post('contact/send',[
		'uses' => 'ContactController@send',
		'as'   => 'contact.send'
	]);


	
Route::get('faq', [
		'uses'	=>	'FaqController@index',
		'as'	=>	'faq.index'
	]);
	
Route::get('lawyer', [
		'uses'	=>	'LawyerController@index',
		'as'	=>	'lawyer.index'
	]);
	
Route::get('lawyer/{lawyer_id}/contract', [
		'uses'	=>	'LawyerController@contract',
		'as'	=>	'lawyer.contract',
		'middleware' => 'auth'
	]);

Route::post('lawyer/{lawyer_id}/hire', [
		'uses'	=>	'LawyerController@hire',
		'as'	=>	'lawyer.hire',
		'middleware' => 'auth'
	]);

Route::post('lawyer/rate', [
		'uses'	=>	'LawyerController@ratehire',
		'as'	=>	'lawyer.rate',
		'middleware' => 'auth'
	]);
	
Route::get('lawyer/{lawyer_id}/showhire', [
		'uses'	=>	'LawyerController@showhire',
		'as'	=>	'lawyer.showhire',
		'middleware' => 'auth'
	]);

Route::get('lawyer/find/{specialid?}', [
		'uses'	=>	'LawyerController@find',
		'as'	=>	'lawyer.find'
	]);
	
// Question 
Route::resource('question', 'QuestionController');

Route::post('question/{id}/comment',[
		'uses' => 'QuestionController@comment',
		'as'   => 'question.store.comment'
	]);

// Blog
Route::resource('blog', 'BlogController');

Route::post('blog/{id}/comment',[
		'uses' => 'BlogController@comment',
		'as'   => 'blog.store.comment'
	]);
	
Route::get('blog/{id}/section',[
		'uses' => 'BlogController@section',
		'as'   => 'blog.section'
	]);
	
Route::post('blog/{id}/comment',[
		'uses' => 'BlogController@comment',
		'as'   => 'blog.store.comment'
	]);	
	
// Foro
Route::resource('forum', 'ForumController');

Route::post('forum/{id}/comment',[
		'uses' => 'ForumController@comment',
		'as'   => 'forum.store.comment'
	]);	
	
Route::get('forum/{id}/lists',[
		'uses' => 'ForumController@lists',
		'as'   => 'forum.lists'
	]);

	
// General
	

// Promocion
Route::resource('promotion', 'PromotionController');


// Users
Route::group(['middleware' => 'auth'], function() {

	Route::get('user/whohire',[
			'uses' => 'UserController@whohire',
			'as'   => 'user.whohire'
		]);
		
	Route::get('user/myhire',[
			'uses' => 'UserController@myhire',
			'as'   => 'user.myhire'
		]);
		
	Route::get('user/mypost',[
			'uses' => 'UserController@mypost',
			'as'   => 'user.mypost'
		]);
		
	Route::get('user/myanswer',[
			'uses' => 'UserController@myanswer',
			'as'   => 'user.myanswer'
		]);	

	Route::get('user/mypromotion',[
			'uses' => 'UserController@mypromotion',
			'as'   => 'user.mypromotion'
	]);	

	Route::get('user/mymoderate',[
			'uses' => 'UserController@mymoderate',
			'as'   => 'user.mymoderate'
	]);	

	Route::get('user/aprove/{id}/comment',[
			'uses' => 'UserController@c_aprove',
			'as'   => 'user.c_aprove'
	]);	

	Route::get('user/reject/{id}/comment',[
			'uses' => 'UserController@c_reject',
			'as'   => 'user.c_reject'
	]);	

	Route::get('user/aprove/{id}/article',[
			'uses' => 'UserController@a_aprove',
			'as'   => 'user.a_aprove'
	]);	

	Route::get('user/reject/{id}/article',[
			'uses' => 'UserController@a_reject',
			'as'   => 'user.a_reject'
	]);	
	

	// Administration

	Route::get('admin/index',[
			'uses' => 'AdminController@index',
			'as'   => 'admin.index'
	]);	


	Route::get('admin/profiles/index',[
			'uses' => 'AdminController@profiles',
			'as'   => 'admin.profiles'
	]);
	
	// Country
	Route::get('admin/country',[
			'uses' => 'AdminController@country',
			'as'   => 'admin.country'
	]);	

	Route::put('admin/country',[
			'uses' => 'AdminController@country_insert',
			'as'   => 'admin.country.insert'
	]);	
	
	Route::post('admin/country/destroy',[
			'uses' => 'AdminController@country_destroy',
			'as'   => 'admin.country.destroy'
	]);	
	
	// Profesion
	Route::get('admin/profession',[
			'uses' => 'AdminController@profession',
			'as'   => 'admin.profession'
	]);	

	Route::put('admin/profession',[
			'uses' => 'AdminController@profession_insert',
			'as'   => 'admin.profession.insert'
	]);	
	
	Route::post('admin/profession/destroy',[
			'uses' => 'AdminController@profession_destroy',
			'as'   => 'admin.profession.destroy'
	]);	
	
	// City
	Route::get('admin/city',[
			'uses' => 'AdminController@city',
			'as'   => 'admin.city'
	]);	

	Route::put('admin/city',[
			'uses' => 'AdminController@city_insert',
			'as'   => 'admin.city.insert'
	]);	
	
	Route::post('admin/city/destroy',[
			'uses' => 'AdminController@city_destroy',
			'as'   => 'admin.city.destroy'
	]);	
	
	// Perfil
	Route::put('admin/profile/{profile}/update',[
			'uses' => 'AdminController@profile_update',
			'as'   => 'admin.profile.update'
	]);	

	Route::get('admin/profile/{id}/edit',[
			'uses' => 'AdminController@profile_edit',
			'as'   => 'admin.profile.edit'
	]);	
	
	Route::get('admin/config/index',[
			'uses' => 'AdminController@config',
			'as'   => 'admin.config'
	]);	
	
	Route::get('admin/promotion/index',[
			'uses' => 'AdminController@promotion',
			'as'   => 'admin.promotion'
	]);	

	
});

Route::resource('user', 'UserController');	

// Authorization

Route::auth();

Route::get('auth/login', [
		'uses'	=>	'Auth\AuthController@getLogin',
		'as'	=>	'auth.login'
	]);


Route::post('auth/login', [
		'uses'	=>	'Auth\AuthController@postLogin',
		'as'	=>	'auth.login'
	]);


Route::get('auth/logout', [
		'uses'	=>	'Auth\AuthController@getLogout',
		'as'	=>	'auth.logout'
	]);

Route::get('user/activation/{token}', [ 
			'uses'  => 'Auth\AuthController@activateUser',
			'as' 	=> 'user.activate'
	]);



/**
 * used for ajax call 
 *
 */
 
Route::get('ajax-city/{countryid}', function($countryid){
    $city = \App\City::where('countryid', '=', $countryid )->lists('name','cityid');
	
    return Response::json($city);
});

Route::post('ajax-lawyersearch', [
				'uses' => 'LawyerController@search',
				'as' => 'lawyer.search'
]);
	



//Route::get('/home', 'HomeController@index');

resources/views/template/partials/footer.blade.php
<footer class="short" id="footer">
				<div class="container">
					<div class="row">
						<div class="col-md-5">
							<a href="demo-law-firm.html" class="logo mb-md">
								<img alt="Porto Website Template" class="img-responsive" width="97" height="32" src="img/demos/law-firm/logo-law-firm-footer.png">
							</a>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu pulvinar magna. Phasellus semper scelerisque purus, et semper nisl lacinia sit amet. Praesent venenatis turpis vitae purus semper, eget sagittis velit venenatis.</p>
						</div>
						<div class="col-md-3 col-md-offset-1">
							<h5 class="mb-sm">Porto Law Firm</h5>
							<ul class="list list-icons mt-xl">
								<li><i class="fa fa-map-marker"></i> <strong>Address:</strong> 1234 Street Name, City Name, United States</li>
								<li><i class="fa fa-envelope"></i> <strong>Email:</strong> <a href="mailto:mail@example.com">mail@example.com</a></li>
							</ul>
						</div>
						<div class="col-md-3">
							<h5 class="mb-sm">Llama</h5>
							<span class="phone">(800) 123-4567</span>
							<ul class="social-icons mt-lg">
								<li class="social-icons-facebook"><a href="http://www.facebook.com/" target="_blank" title="Facebook"><i class="fa fa-facebook"></i></a></li>
								<li class="social-icons-twitter"><a href="http://www.twitter.com/" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></li>
								<li class="social-icons-linkedin"><a href="http://www.linkedin.com/" target="_blank" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="footer-copyright">
					<div class="container">
						<div class="row">
							<div class="col-md-12">
								<p>&copy; Copyright Mi Caso Legal 2016. | <a href="{{ route('contact.index')}}">Contactanos</a> | <a href="{{ route('faq.index')}}">FAQ</a></p>
							</div>
						</div>
					</div>
				</div>
</footer>
<!-- Footer -->

resources/views/template/partials/nav.blade.php
	<header id="header" class="header-no-border-bottom" data-plugin-options="{'stickyEnabled': true, 'stickyEnableOnBoxed': true, 'stickyEnableOnMobile': true, 'stickyStartAt': 115, 'stickySetTop': '-115px', 'stickyChangeLogo': false}" style="min-height: 175px;">
				<div class="header-body" style="top: 0px;">
					<div class="header-container container">
						<div class="header-row">
							<div class="header-column">
								<div class="header-logo">
									<a href="{{ route('index') }}">
										<img alt="Porto" width="164" height="54" data-sticky-width="82" data-sticky-height="40" data-sticky-top="33" src="img/demos/law-firm/logo-law-firm.png">
									</a>
								</div>
							</div>
							<div class="header-column">
								<ul class="header-extra-info">
									<li>
										<div class="feature-box feature-box-call feature-box-style-2">
											<div class="feature-box-icon">
												<i class="icon-call-end icons"></i>
											</div>
											<div class="feature-box-info">
												<h4 class="mb-none">(800) 123-4567</h4>
											</div>
										</div>
									</li>
									<li class="hidden-xs">
										<div class="feature-box feature-box-mail feature-box-style-2">
											<div class="feature-box-icon">
												<i class="icon-envelope icons"></i>
											</div>
											<div class="feature-box-info">
												<h4 class="mb-none"><a href="mailto:mail@example.com">mail@example.com</a></h4>
											</div>
										</div>
									</li>
								</ul>
							</div>
						</div>
					</div>
					<div class="header-container header-nav header-nav-bar header-nav-bar-primary">
						<div class="container">
							<button class="btn header-btn-collapse-nav" data-toggle="collapse" data-target=".header-nav-main">
								Menu <i class="fa fa-bars"></i>
							</button>
							<div class="header-search visible-lg">
								<form id="searchForm" action="page-search-results.html" method="get" novalidate="novalidate">
									<div class="input-group">
										<input type="text" class="form-control" name="q" id="q" placeholder="Search..." required="" aria-required="true">
										<span class="input-group-btn">
											<button class="btn btn-default" type="submit"><i class="icon-magnifier icons"></i></button>
										</span>
									</div>
								</form>
							</div>
							<div class="header-nav-main header-nav-main-light header-nav-main-effect-1 header-nav-main-sub-effect-1 collapse" aria-expanded="false" style="height: 0px;">
								<nav>
									<ul class="nav nav-pills" id="mainNav">
										<!-- <li class="{!! Route::is('promotion.index') ? 'active' : '' !!}" >
											<a href="{{ route('promotion.index')}}"  title="Promociones" ></a>
										</li>
										-->
										<li class="{!! Route::is('index') ? 'active' : '' !!}" >
											<a href="{{ route('index')}}" >Home</a>
										</li>
										<li class="{!! Route::is('about') ? 'active' : '' !!}" >
											<a href="{{ route('about')}}" >Quienes Somos</a>
										</li>
										<li class="{!! Route::is('lawyer.*') ? 'active' : '' !!}">
											<a href="{{ route('lawyer.index')}}">Abogados</a>
										</li>
										<li class="{!! Route::is('blog.*') ? 'active' : '' !!}">
											<a href="{{ route('blog.index') }}">Articulos</a>
										</li>					
										<li class="{!! Route::is('forum.*') ? 'active' : '' !!}">
											<a href="{{ route('forum.index') }}">Comunidad</a>
										</li>					

										<li class="{!! Route::is('question.*') ? 'active' : '' !!}">
											<a href="{{ route('question.index') }}">Consultas en Linea</a>
										</li>
										
										<li class="dropdown">
											@if(Auth::guest())
											<a href="#" class="dropdown-toggle" data-toggle="dropdown">Usuarios </a>
											<ul class="dropdown-menu">
												<li>
												  <a href="{{ route('auth.login') }}"><i class="fa fa-sign-in fa-fw" aria-hidden="true"></i> Login</a>
												</li>								
												<li>
													<a href="{{ route('user.create')}}"><i class="fa fa-user-plus fa-fw" aria-hidden="true"></i> Registrate</a>
												</li>                            
											</ul>
											@else
											<a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ Auth::user()->username}} <b class="caret"></b></a>
											<ul class="dropdown-menu">

												<li>
													<a href="{{ route('user.edit',Auth::user()->loginid) }}"><i class="fa fa-user fa-fw" aria-hidden="true"></i> Mi cuenta</a>
												</li>
												<li>
													<a href="{{ route('user.show',Auth::user()->loginid) }}"><i class="fa fa-newspaper-o  fa-fw" aria-hidden="true"></i> Mi Actividad</a>
												</li>							
												@if(Auth::user()->level == LEVEL_ADMIN)
												<li class="divider"></li>
												<li>
													<a href="{{ route('admin.index') }}">Administracion</a>						
												</li>
												@endif
												<li>
												  <a href="{{ route('auth.logout') }}">Logout</a>
												</li>
											</ul>
											@endif						
										</li>									
									</ul>
								</nav>
							</div>
						</div>
					</div>
				</div>
	</header>
			
   

resources/views/template/partials/sectionbar.blade.php
   <!-- Sidebar Column -->

   @if(isset($sections))
    <div class="col-md-3">
		<div class="list-group">
		<a href="{{ route('blog.index')}}" class="list-group-item {!! Route::is('blog.index') ? 'active' : '' !!}">Todos los Articulos</a>
		@foreach($sections as $section)
			<a href="{{ route('blog.section', $section->sectionid) }}" class="list-group-item {!! (Route::getCurrentRequest()->getUri() == route('blog.section', $section->sectionid)) ? 'active' : '' !!}">{{ $section->name }}</a>
		@endforeach	
		</div>
	</div>
   @endif

resources/views/template/partials/sidebar.blade.php
   <!-- Sidebar Column -->
	<div class="col-md-3">
		<div class="list-group">
			<a href="{{ route('user.show',Auth::user()->loginid) }}" class="list-group-item {!! Route::is('user.show') ? 'active' : '' !!}">Mis Estadisticas</a>
			<a href="{{ route('user.mypost') }}" class="list-group-item {!! Route::is('user.mypost') ? 'active' : '' !!}">Mis Preguntas</a>
			<a href="{{ route('user.myanswer') }}" class="list-group-item {!! Route::is('user.myanswer') ? 'active' : '' !!}">Mis Respuestas</a>
			<a href="{{ route('user.mymoderate') }}" class="list-group-item {!! Route::is('user.mymoderate') ? 'active' : '' !!}">Moderaciones</a>
			<a href="{{ route('user.mypromotion') }}" class="list-group-item {!! Route::is('user.mypromotion') ? 'active' : '' !!}">Promociones</a>						
			<a href="{{ route('user.myhire') }}" class="list-group-item {!! Route::is('user.myhire') ? 'active' : '' !!}">Servicios Contratados</a>			
			<a href="{{ route('user.whohire') }}" class="list-group-item {!! Route::is('user.whohire') ? 'active' : '' !!}">¿Quien me contrato?</a>			
		</div>
	</div>

resources/views/template/partials/sidenav.blade.php
  <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ route('admin.index') }}">Administración</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li>
                    <a href="{{ route('index') }}" ><i class="fa fa-home fa-fw"></i>Pagina Principal</a>                    
                </li>
                                
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <a href="{{ route('admin.profiles') }}"><i class="fa fa-fw fa-group"></i> Usuarios</a>
                    </li>
                   <li>
                        <a href="{{ route('admin.config')}}"><i class="fa fa-fw fa-wrench"></i> Configuraci&oacute;n</a>
                    </li>
                   <li>
                        <a href="{{ route('admin.promotion')}}"><i class="fa fa-fw fa-table"></i> Promociones</a>
                    </li>
                   <!--  <li>
                        <a href="forms.html"><i class="fa fa-fw fa-edit"></i> Forms</a>
                    </li>
                    <li>
                        <a href="bootstrap-elements.html"><i class="fa fa-fw fa-desktop"></i> Bootstrap Elements</a>
                    </li>
                    <li>
                        <a href="bootstrap-grid.html"><i class="fa fa-fw fa-wrench"></i> Bootstrap Grid</a>
                    </li>                                        -->
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>