app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', [
	'as' 	=>	'index', 
	'uses'	=>	'MainController@index'
	]);
	
Route::get('about', [
		'uses'	=>	'MainController@about',
		'as'	=>	'about'
	]);
	
Route::get('contact', [
		'uses'	=>	'ContactController@index',
		'as'	=>	'contact.index'
	]);
	
Route::post('contact/send',[
		'uses' => 'ContactController@send',
		'as'   => 'contact.send'
	]);


	
Route::get('faq', [
		'uses'	=>	'FaqController@index',
		'as'	=>	'faq.index'
	]);
	
Route::get('lawyer', [
		'uses'	=>	'LawyerController@index',
		'as'	=>	'lawyer.index'
	]);
	
Route::get('lawyer/{lawyer_id}/contract', [
		'uses'	=>	'LawyerController@contract',
		'as'	=>	'lawyer.contract',
		'middleware' => 'auth'
	]);

Route::post('lawyer/{lawyer_id}/hire', [
		'uses'	=>	'LawyerController@hire',
		'as'	=>	'lawyer.hire',
		'middleware' => 'auth'
	]);

Route::post('lawyer/rate', [
		'uses'	=>	'LawyerController@ratehire',
		'as'	=>	'lawyer.rate',
		'middleware' => 'auth'
	]);
	
Route::get('lawyer/{lawyer_id}/showhire', [
		'uses'	=>	'LawyerController@showhire',
		'as'	=>	'lawyer.showhire',
		'middleware' => 'auth'
	]);

Route::get('lawyer/find/{specialid?}', [
		'uses'	=>	'LawyerController@find',
		'as'	=>	'lawyer.find'
	]);
	
// Question 
Route::resource('question', 'QuestionController');

Route::post('question/{id}/comment',[
		'uses' => 'QuestionController@comment',
		'as'   => 'question.store.comment'
	]);

// Blog
Route::resource('blog', 'BlogController');

Route::post('blog/{id}/comment',[
		'uses' => 'BlogController@comment',
		'as'   => 'blog.store.comment'
	]);
	
Route::get('blog/{id}/section',[
		'uses' => 'BlogController@section',
		'as'   => 'blog.section'
	]);
	
Route::post('blog/{id}/comment',[
		'uses' => 'BlogController@comment',
		'as'   => 'blog.store.comment'
	]);	
	
// Foro
Route::resource('forum', 'ForumController');

Route::post('forum/{id}/comment',[
		'uses' => 'ForumController@comment',
		'as'   => 'forum.store.comment'
	]);	
	
Route::get('forum/{id}/lists',[
		'uses' => 'ForumController@lists',
		'as'   => 'forum.lists'
	]);

	
// General
	

// Promocion
Route::resource('promotion', 'PromotionController');


// Users
Route::group(['middleware' => 'auth'], function() {

	Route::get('user/whohire',[
			'uses' => 'UserController@whohire',
			'as'   => 'user.whohire'
		]);
		
	Route::get('user/myhire',[
			'uses' => 'UserController@myhire',
			'as'   => 'user.myhire'
		]);
		
	Route::get('user/mypost',[
			'uses' => 'UserController@mypost',
			'as'   => 'user.mypost'
		]);
		
	Route::get('user/myanswer',[
			'uses' => 'UserController@myanswer',
			'as'   => 'user.myanswer'
		]);	

	Route::get('user/mypromotion',[
			'uses' => 'UserController@mypromotion',
			'as'   => 'user.mypromotion'
	]);	

	Route::get('user/mymoderate',[
			'uses' => 'UserController@mymoderate',
			'as'   => 'user.mymoderate'
	]);	

	Route::get('user/aprove/{id}/comment',[
			'uses' => 'UserController@c_aprove',
			'as'   => 'user.c_aprove'
	]);	

	Route::get('user/reject/{id}/comment',[
			'uses' => 'UserController@c_reject',
			'as'   => 'user.c_reject'
	]);	

	Route::get('user/aprove/{id}/article',[
			'uses' => 'UserController@a_aprove',
			'as'   => 'user.a_aprove'
	]);	

	Route::get('user/reject/{id}/article',[
			'uses' => 'UserController@a_reject',
			'as'   => 'user.a_reject'
	]);	
	

	// Administration

	Route::get('admin/index',[
			'uses' => 'AdminController@index',
			'as'   => 'admin.index'
	]);	


	Route::get('admin/profiles/index',[
			'uses' => 'AdminController@profiles',
			'as'   => 'admin.profiles'
	]);
	
	// Country
	Route::get('admin/country',[
			'uses' => 'AdminController@country',
			'as'   => 'admin.country'
	]);	

	Route::put('admin/country',[
			'uses' => 'AdminController@country_insert',
			'as'   => 'admin.country.insert'
	]);	
	
	Route::post('admin/country/destroy',[
			'uses' => 'AdminController@country_destroy',
			'as'   => 'admin.country.destroy'
	]);	
	
	// Profesion
	Route::get('admin/profession',[
			'uses' => 'AdminController@profession',
			'as'   => 'admin.profession'
	]);	

	Route::put('admin/profession',[
			'uses' => 'AdminController@profession_insert',
			'as'   => 'admin.profession.insert'
	]);	
	
	Route::post('admin/profession/destroy',[
			'uses' => 'AdminController@profession_destroy',
			'as'   => 'admin.profession.destroy'
	]);	
	
	// City
	Route::get('admin/city',[
			'uses' => 'AdminController@city',
			'as'   => 'admin.city'
	]);	

	Route::put('admin/city',[
			'uses' => 'AdminController@city_insert',
			'as'   => 'admin.city.insert'
	]);	
	
	Route::post('admin/city/destroy',[
			'uses' => 'AdminController@city_destroy',
			'as'   => 'admin.city.destroy'
	]);	
	
	// Perfil
	Route::put('admin/profile/{profile}/update',[
			'uses' => 'AdminController@profile_update',
			'as'   => 'admin.profile.update'
	]);	

	Route::get('admin/profile/{id}/edit',[
			'uses' => 'AdminController@profile_edit',
			'as'   => 'admin.profile.edit'
	]);	
	
	Route::get('admin/config/index',[
			'uses' => 'AdminController@config',
			'as'   => 'admin.config'
	]);	
	
	Route::get('admin/promotion/index',[
			'uses' => 'AdminController@promotion',
			'as'   => 'admin.promotion'
	]);	

	
});

Route::resource('user', 'UserController');	

// Authorization

Route::auth();

Route::get('auth/login', [
		'uses'	=>	'Auth\AuthController@getLogin',
		'as'	=>	'auth.login'
	]);


Route::post('auth/login', [
		'uses'	=>	'Auth\AuthController@postLogin',
		'as'	=>	'auth.login'
	]);


Route::get('auth/logout', [
		'uses'	=>	'Auth\AuthController@getLogout',
		'as'	=>	'auth.logout'
	]);

Route::get('user/activation/{token}', [ 
			'uses'  => 'Auth\AuthController@activateUser',
			'as' 	=> 'user.activate'
	]);



/**
 * used for ajax call 
 *
 */
 
Route::get('ajax-city/{countryid}', function($countryid){
    $city = \App\City::where('countryid', '=', $countryid )->lists('name','cityid');
	
    return Response::json($city);
});

Route::post('ajax-lawyersearch', [
				'uses' => 'LawyerController@search',
				'as' => 'lawyer.search'
]);
	



//Route::get('/home', 'HomeController@index');

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Laracasts\Flash\Flash;


use App\Factories\ActivationFactory;

use App\Http\Requests;
use App\Http\Requests\UserRequest;
use App\Http\Requests\UserUpdateRequest;

use App\Country;
use App\City;
use App\User;
use App\Lawyer;
use App\Profesion;
use App\Article;
use App\Comment;
use App\Promotion;
use App\Hire;
use App\Code;
use App\CodePromotion;

class UserController extends Controller
{
	
	
	protected $activationFactory;

	public function __construct(ActivationFactory $activationFactory)
	{		
		$this->activationFactory = $activationFactory;
	}
	
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		
    }
	/**
	*
	* Display a listing of my moderation
	*
	*/
	public function mymoderate()
	{
		$id = \Auth::user()->loginid;
		$level = \Auth::user()->level;
		$admin_amoderates=array();
		$admin_cmoderates=array();
		
		// Comment to aprove by user
		$cmoderates = Comment::with('article')->whereHas('article', function ($query) use ($id) {
							$query->where('loginid','=', $id);			
					 })->where('type','=',COMMENT_MODERATE_USER)->get();

		
		if($level == LEVEL_ADMIN)
		{
			// Articles to moderate by admin
			$admin_amoderates = Article::wherein('type',[ARTICLE_BLOG_MODERATE,ARTICLE_QUESTION_MODERATE,ARTICLE_FORUM_MODERATE])->get(); 
			
			// Comment to aprove by admin
			$admin_cmoderates = Comment::with('article')->where('type','=',COMMENT_MODERATE)->get();
		}
		
		return view('user.mymoderate')
					->with('cmoderates',$cmoderates)
					->with('admin_amoderates',$admin_amoderates)
					->with('admin_cmoderates',$admin_cmoderates);
		
	}
	
	/**
	*
	* Display a listing of my promotion
	*
	*/
	public function mypromotion()
	{
		$id = \Auth::user()->loginid;
		$promotions = Promotion::where('active','=',1)->where('loginid','=',$id)->simplePaginate(15);
		
		return view('user.mypromotion')
				->with('promotions',$promotions);
	}
	
	/**
	*
	* Display a listing of my questions
	*
	*/
	public function mypost()
	{
		$id = \Auth::user()->loginid;
		
		$questions = Article::Question()->where('loginid','=',$id)->simplePaginate(15);
		
		return view('user.mypost')
				->with('questions',$questions);
	}
	
	/**
	*
	* Display a listing of my questions
	*
	*/
	public function myanswer()	
	{
		$id = \Auth::user()->loginid;
		
		$articles =  Article::whereHas('comment', function ($query) use ($id) {
							$query->where('loginid','=', $id);			
					})->paginate(15);
					
		$articles->each(function($article) {
			$article->comment;
		});
		

		//$comments = Comment::where('loginid','=',$id)->simplePaginate(15);
				
		return view('user.myanswer')
				->with('articles',$articles);
	}
	
	/**
	*
	* Display a listing of my hires
	*
	*/
	public function myhire()	
	{
		$user_id = \Auth::user()->loginid;
		
		$hires =  Hire::where([
					['user_id','=',$user_id],
					['active','=',1]
				])->paginate(15);
					
		$hires->each(function($hire) {
			$hire->lawyers;
		});

			
		return view('user.myhire')
				->with('hires',$hires);
	}
	
	/**
	*
	* Display a listing of who hire me
	*
	*/
	public function whohire()	
	{
		$user_id = \Auth::user()->loginid;
		$hires = null;

        $user = User::find($user_id);
		if($user->is_lawyer == 1) {		
			
			$user->lawyer;
			$hires =  Hire::where([
					['lawyer_id','=',$user_id],
					['active','=',1]
				])->paginate(15);
			$hires->each(function($hire) {
				$hire->user;
			});
					
		}
			
		return view('user.whohire')
			->with('hires',$hires);
	}

	
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
		$country = Country::orderBy('name', 'ASC')->lists('name', 'countryid');		
		$profesion = Profesion::orderBy('name', 'ASC')->lists('name', 'profesionid');
		$client = Code::Client()->get();
		$language = Code::Language()->get();
		$service =  Code::OfferService()->get();
		$fare =  Code::Fare()->get();
		$payment_mode =  Code::PaymentMode()->get();
		$payment_type=  Code::PaymentType()->get();
		$specialities=  Code::Specialities()->get();
		

		return view('user.create')
			   ->with('country',$country)
			   ->with('profesion',$profesion)
			   ->with('client',$client)
			   ->with('language',$language)
			   ->with('service',$service)
			   ->with('fare',$fare)
			   ->with('payment_mode',$payment_mode)
			   ->with('payment_type',$payment_type)
			   ->with('specialities',$specialities);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        //
		
		//MANIPULACION DE IMAGENES
		$name="";
	
		DB::beginTransaction();
		try{
			
			if($request->file('image'))
			{
				$file = $request->file('image');
				$name = 'micasolegal_' . time() . '.'. $file->getClientOriginalExtension();
				$path = public_path(). '/images/user/';
				$file->move($path, $name);
			}
			
			
			$user = new User($request->only(['username','password','email','image_path','countryid','cityid']));
			$user->is_lawyer = $request->has('is_lawyer') ;
			$user->password = bcrypt($request->password);
			$user->image_path = $name;
			$user->save();
						
			if($request->input('is_lawyer',false) == true )
			{ 
				$lawyer = new Lawyer($request->only(['name','lastname','phone', 'postalcode','address','resume','profesionid', 'experience','partnership','service','schedule']));
				$lawyer->login()->associate($user);
				$lawyer->save();
				
				
				$sync_client = null;
				
				if($request->client)
				foreach($request->client As $value){
				  $sync_client[$value] = array('type' => 'client');
				}			  
				
				if($request->language)
				foreach($request->language As $value){
				  $sync_client[$value] = array('type' => 'language');
				}	
				
				if($request->offer_service)
				foreach($request->offer_service As $value){
				  $sync_client[$value] = array('type' => 'offer_service');
				}
				
				if($request->fare)
				foreach($request->fare As $value){
				  $sync_client[$value] = array('type' => 'fare');
				}
				
				if($request->payment_mode)
				foreach($request->payment_mode As $value){
				  $sync_client[$value] = array('type' => 'payment_mode');
				}
				
				if($request->payment_type)
				foreach($request->payment_type As $value){
				  $sync_client[$value] = array('type' => 'payment_type');
				}
				
				if($request->special)
				foreach($request->special As $value){
				  $sync_client[$value] = array('type' => 'special');
				}
				// Save code table
				if($sync_client) {
					$lawyer->code()->sync($sync_client);
				}

			}
			
			// Send Email
			$this->activationFactory->sendActivationMail($user);
		
		} catch(ValidationException $e) {
			DB::rollback(); 
			return redirect()->route('user.create')
					->withErrors($e->getErrors())
					->withInput();
			
		} catch(\Exception $e){
			DB::rollback();
			throw $e;
		}
		DB::commit();
		
		Flash::warning("Se ha enviado el codigo de activación a su correo.Por favor revise." )->important();
		return redirect()->route('index');
    }

    /**
     * Display the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
		
		$CountArticles = Article::get()->count();
		$CountComment = Comment::get()->count();

		
		$CountMyArticles = Article::where('loginid','=',$id)->count();
		$CountMyComment = Comment::where('loginid','=',$id)->count();
		
		return view('user.show')
			->with('CountArticles',$CountArticles)
			->with('CountComment',$CountComment)
			->with('CountMyArticles',$CountMyArticles)
			->with('CountMyComment',$CountMyComment);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
		$user = User::find($id);		
		$country = Country::orderBy('name', 'ASC')->lists('name', 'countryid');		
		$city = City::where('countryid','=', $user->countryid)->lists('name','cityid');
		
		
		
		if(\Auth::user()->is_lawyer == 1)
		{
			$user->lawyer;
			
			$load_code = $user->lawyer->code()->lists('value','t101_code_lawyers.codeid')->toArray();
						
			$profesion = Profesion::orderBy('name', 'ASC')->lists('name', 'profesionid');		
			
			$client = Code::Client()->get();			
			$language = Code::Language()->get();
			$service =  Code::OfferService()->get();			
			$fare = Code::Fare()->get();			
			$payment_mode =  Code::PaymentMode()->get();			
			$payment_type=  Code::PaymentType()->get();
			$specialities=  Code::Specialities()->get();
			$code_promotion = CodePromotion::get();
		
			return view('user.edit_lawyer')
					->with('country',$country)
					->with('city',$city)
					->with('profesion',$profesion)
					->with('user',$user)
					->with('client',$client)
					->with('language',$language)
					->with('service',$service)
					->with('fare',$fare)
					->with('payment_mode',$payment_mode)
					->with('payment_type',$payment_type)
					->with('load_code',$load_code)
					->with('code_promotion',$code_promotion)
					->with('specialities',$specialities);
					
		} else
			return view('user.edit_single')
					->with('user',$user)
					->with('country',$country)
					->with('city',$city);
;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateRequest $request, $id)
    {
        //
		$lawyer_update=false;		
		$oldfile = "";
		
		$user = User::find($id);
		
		DB::beginTransaction();
		try{
			
			if($request->file('image'))
			{
				$file = $request->file('image');

resources/views/user/edit_single.blade.php
@extends('template.main')

 
@section('content')

  <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Mi Cuenta</h1>
                <ol class="breadcrumb">
                    <li><a href="{{ route('index') }}">Home</a>
                    </li>
                    <li class="active">Mi Cuenta</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <div class="col-lg-12">
				<div class="row">					
				  <div class="col-md-12">
			
					{!! Form::open(['route' => ['user.update',$user], 'method' => 'PUT', 'files' => 'true']) !!}
					<div class="row">
						<div class="col-md-12">
						@if (count($errors) > 0)
								<div class="alert alert-danger">
									<ul>
										@foreach ($errors->all() as $error)
											<li>{{ $error }}</li>
										@endforeach
									</ul>
								</div>
						@endif
						</div>
					 <div class="col-md-push-6 col-md-6 text-center"> 
							<br/>
							<div class="form-group text-center">
								<label class="btn btn-primary btn-file">
									Cargar Imagen {!! Form::file('image',['id' => 'file_show', 'style'=> 'display:none']) !!}
								</label>		
								
								<img id="image_show" class="img-responsive" width="400px" src='{!! ($user->image_path) ? asset("images/user/".$user->image_path) :  asset("/images/default-user.png") !!}' />
							</div>
					</div> 
					
					 <div class="col-md-pull-6 col-md-6">
						<br>
						<div class="form-group">
							{!! Form::label('username', 'Nombre del Usuario') !!}
							<div class="form-control-static text-muted">{{ $user->username }}</div>					
						</div>
						
						<div class="form-group">
							{!! Form::label('email', 'Correo Electronico') !!}
							<div class="form-control-static text-muted">{{ $user->email }}</div>					
						</div>
										
						<div class="form-group">
							{!! Form::label('password', 'Clave de ingreso') !!}
							{!! Form::password('password', ['class' => 'form-control']) !!}
						</div>
						
						<div class="form-group">
							{!! Form::label('password_confirmation', 'Retipee la clave de ingreso') !!}
							{!! Form::password('password_confirmation', ['class' => 'form-control']) !!}
						</div>				
						
						<div class="form-group">
							{!! Form::label('countryid', 'Pais') !!}
							{!! Form::select('countryid', $country ,  $user->countryid, ['class' => 'form-control']) !!}
						</div>
						
						<div class="form-group">
							{!! Form::label('cityid', 'Ciudad/Provincia') !!}
							{!! Form::select('cityid', $city, $user->cityid, ['class' => 'form-control']) !!}
						</div>
									
					</div>
					
					
					<div class="col-md-12">			
						<div class="form-group">
							{!! Form::submit('Actualizar', ['class' => 'btn btn-primary']) !!}					
						</div>			
					</div>											
					
				 </div>
				{!! Form::close() !!}
			   </div>
			</div>	
           </div>
        </div>
        <!-- /.row -->
		
    </div>
    <!-- /.container -->
	 
@endsection


@section('js')
	<script src="{{ asset('js/custom.js') }}"></script>
	<script src="{{ asset('js/signup.js') }}"></script>
@endsection

resources/views/user/myanswer.blade.php
@extends('template.main')

 
@section('content')

	<div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Mi Actividad
                    <small>Eventos</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="{{ route('index') }}">Home</a>
                    </li>
                    <li class="active">Mi Actividad</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            @include('template.partials.sidebar')
			<!-- Posted Comments -->
			<div class="col-md-9">
			@foreach($articles as $article)
				 <div class="row">				   
					<div class="col-md-12">
						<span><a href="{{ route('question.show',$article->articleid) }}">{{ $article->title }}</a></span>						
						<p><strong>Respuestas:</strong></p>
						<div class="row">						
							<div class="col-md-11 col-md-offset-1"> 
							  <ul class="list-unstyled">
							  @foreach($article->comment as $comment)
								 <li> 
								    <i class="fa fa-clock-o"></i>
									<small>{{ $comment->created_at->diffForHumans() }}:</small>
									<span>{{ $comment->ShortText }} </span>
								 </li>
								@endforeach 
							</ul>
							</div>
						</div>
					</div>
				 </div>
				 <hr>
			@endforeach
			</div>			
			{{ $articles->links() }}
        </div>
        <!-- /.row -->

    </div>


@endsection

resources/views/user/myhire.blade.php
@extends('template.main')

 
@section('content')

	<div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Mi Actividad
                    <small>Eventos</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="{{ route('index') }}">Home</a>
                    </li>
                    <li class="active">Mi Actividad</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            @include('template.partials.sidebar')
			<div class="col-md-9">
				 <div class="row">				   
						<div class="col-md-12">
							<table class="table table-responsive table-striped">
							   <tbody>
							   @foreach($hires as $hire)
								  <tr>
								    <td class="text-nowrap"><i class="fa fa-legal fa-lg" style="color:lightblue;text-shadow: 1px 1px 1px gray;"></i></td>
									<td class="text-nowrap"><a href="{{ route('lawyer.showhire',$hire->lawyer_id) }}">{{ $hire->lawyers->name." ".$hire->lawyers->lastname }}</a></td>
									<td class="text-nowrap"><i class="fa fa-clock-o"></i><small> {{ $hire->created_at->diffForHumans() }}</small> </td>
									<td><small>{{ $hire->message }}</small></td>
								  </tr>
								@endforeach
							   </tbody>
							</table>
						</div>
				</div>
			</div>
			{{ $hires->links() }}
        </div>
        <!-- /.row -->

    </div>


@endsection

resources/views/user/mypost.blade.php
@extends('template.main')

 
@section('content')

	<div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Mi Actividad
                    <small>Eventos</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="{{ route('index') }}">Home</a>
                    </li>
                    <li class="active">Mi Actividad</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            @include('template.partials.sidebar')
			<!-- Posted Articles -->
			<div class="col-md-9">
			 <div class="row">				   
					<div class="col-md-12">
						<table class="table table-responsive table-striped">
						   <tbody>
						   @foreach($questions as $question)
						      <tr>
								<td class="text-nowrap"><i class="fa fa-question fa-lg" style="color:lightblue;text-shadow: 1px 1px 1px gray;"></i></td>
								<td><a href="{{ route('question.show',$question->articleid) }}">{{ $question->title }}</a></td>
								<td class="text-nowrap"><i class="fa fa-clock-o"></i><small> {{ $question->created_at->diffForHumans() }}</small> </td>
							  </tr>
							@endforeach
						   </tbody>
						</table>
				    </div>
			</div>
 		    <hr>			
			</div>			
			{{ $questions->render() }}
        </div>
        <!-- /.row -->

    </div>


@endsection

resources/views/user/mypromotion.blade.php
@extends('template.main')

 
@section('content')

	<div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Mi Actividad
                    <small>Eventos</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="{{ route('index') }}">Home</a>
                    </li>
                    <li class="active">Mi Actividad</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            @include('template.partials.sidebar')
			<!-- Posted Articles -->
			<div class="col-md-9">
			<a class="btn btn-primary" href="{{ route('promotion.create') }}"><i class="fa fa-file-text-o fa-fw"></i>Nueva Promoción</a>
			<hr>
			
				 <div class="row">				   
					<div class="col-md-12">
						<table class="table table-responsive table-striped">
						   <tbody>
						   @foreach($promotions as $promotion)
						      <tr>
								<td><i class="fa fa-gift fa-lg" style="color:lightblue;text-shadow: 1px 1px 1px gray;"></i></td>
								<td><a href="{{ route('promotion.edit',$promotion->promotionid) }}">{{ $promotion->name }}</a></td>
								<td class="text-nowrap"><i class="fa fa-clock-o"></i><small> {{ $promotion->created_at->diffForHumans() }}</small> </td>
								<td class="text-nowrap"><small>{{ $promotion->start_date }} al {{ $promotion->end_date }}</small></td>
							  </tr>
							@endforeach
						   </tbody>
						</table>
				    </div>
				 </div>
				 <hr>
			</div>			
			{{ $promotions->render() }}
        </div>
        <!-- /.row -->

    </div>


@endsection